### ISSUE TITLE
Elaborate why auth modes are not suppored

### ISSUE THREAD

**Issue by bwesterb** [bwesterb/draft-westerbaan-cfrg-hpke-xyber768d00#4]
As suggested by @thomwiggers

**Comment by bwesterb** [comment]
Fixed by 8296793773314fc8c1d35f2c8e2e890ff1b145e7

**Comment by thomwiggers** [comment]
I might have put it in the security considerations, but leading off with it may be better for visibility. Other than that specific color of the bike shed, LGTM
