### ISSUE TITLE
Have any plan to update to X25519MLKEM768?

### ISSUE THREAD

**Issue by dajiaji** [bwesterb/draft-westerbaan-cfrg-hpke-xyber768d00#8]
Hi @bwesterb,

I am developing an HPKE library called [hpke-js](https://github.com/dajiaji/hpke-js) and have been experimentally implementing your draft specification (See [@hpke/hybridkem-x25519-kyber768](https://github.com/dajiaji/hpke-js/tree/main/packages/hybridkem-x25519-kyber768)).

ML-KEM was officially released as FIPS 203 in August. Do you have plans to update this draft specification to follow ML-KEM? I recently discovered this repository: [draft-irtf-cfrg-hybrid-kems](https://github.com/cfrg/draft-irtf-cfrg-hybrid-kems) and I am wondering if your efforts will be integrated into this repository.

If you plan to continue updating this draft, I can assist with updating the test vectors, etc., as hpke-js already supports ML-KEM in my development environment.

**Comment by bwesterb** [comment]
This draft (westerbaan-cfrg-hpke-xyber768d00) will not be updated to ML-KEM.

I don't expect output of draft-irtf-cfrg-hybrid-kems anytime soon.

If you want something soon, have a look at [X-Wing](http://github.com/dconnolly/draft-connolly-cfrg-xwing-kem) and its HPKE integration. It could be that the private key format is changed this month. Otherwise it's final.

**Comment by dajiaji** [comment]
Thank you for the information. Okay, I will stop updating my X25519Kyber768 implementation. While I was aware of X-Wing, I hadn't checked its details yet. I will take a look at the draft.

**Comment by bwesterb** [comment]
Just wanted to let you know that [X-Wing](https://github.com/dconnolly/draft-connolly-cfrg-xwing-kem) has an HPKE identifier now: 25722.

**Comment by dajiaji** [comment]
Thanks! I wanted to know that information.

**Comment by dajiaji** [comment]
@bwesterb Hey, I have experimentally implemented X-Wing in hpke-js (see [@hpke/hybridkem-x-wing](https://github.com/dajiaji/hpke-js/tree/main/packages/hybridkem-x-wing)).

Is it correct to assume that the test vectors described in the X-Wing draft are not up to date with the latest spec, as indicated by the "TODO" notes? If they are already being prepared, that's fine, but if needed, I can create a PR for the test vectors to help verify interoperability.

**Comment by bwesterb** [comment]
The test vectors are up to date. The TODO is to add more extensive test vectors.

> Hey, I have experimentally implemented X-Wing in hpke-js (see [@hpke/hybridkem-x-wing](https://github.com/dajiaji/hpke-js/tree/main/packages/hybridkem-x-wing)).

Cool!

**Comment by dajiaji** [comment]
> The test vectors are up to date. The TODO is to add more extensive test vectors.

Okay, thanks... It seems there is something wrong with my implementation. I'll check it.

**Comment by dajiaji** [comment]
@bwesterb Is the code that generated the test vectors published? I'd like to check it.

The results from the ML-KEM::KeyGen_internal (generateKeyPairDerand) do not seem to match. It might be my library that is at fault, but it has passed the official test vectors...

Sorry for bothering you.

**Comment by bwesterb** [comment]
https://github.com/dconnolly/draft-connolly-cfrg-xwing-kem/tree/main/spec

**Comment by dajiaji** [comment]
There was a problem on my side. Finally, I have successfully obtained results consistent with the test vectors.

As of version 0.3.0, X-Wing now runs properly on various JavaScript runtimes including web browsers and, of course, cloudflare workers :-)

**Comment by bwesterb** [comment]
Cool!
